### ISSUE TITLE
[2.2.2.2] AppNotice class holds static reference to the activity which causes memory leaks

### ISSUE THREAD

**Issue by mariuszvimn** [Crownpeak/AppNotice_Triangle_android_aar#23]
Just what title says. Attaching screenshot from decompiled class file
![screen shot 2018-09-13 at 12 05 02](https://user-images.githubusercontent.com/43236644/45482031-4737bc80-b74d-11e8-877a-4c2d5dce92fb.png)

**Comment by vinaychencharam** [comment]
Hi @mariuszvimn, try the new version of AppNoticeSDK (2.2.2.4). Hope this works for you. Let me know if you have any issues.
Thanks
