### ISSUE TITLE
AppNotice_Activity shown after tapping "Decline All"

### ISSUE THREAD

**Issue by damianvimn** [Crownpeak/AppNotice_Triangle_android_aar#27]
After tapping on "Decline All" button `AppNotice_Activity` is shown. Is there a possibility to not show this activity? Currently user can't use application after tapping on "Decline All". I tried to skip it somehow by using `AppNotice_Callback` but no callback is called after tapping "Decline All". Please help.

**Comment by vinaychencharam** [comment]
Hi @damianvimn, may i know to which country the device is set to ? For Explicit Non-GDPR countries you need to give consent to use the application.

**Comment by damianvimn** [comment]
Actually this is very helpful information. So for Non-GDPR countries there is no possibility to use app without consents?

**Comment by jwheeler66** [comment]
You can in non gdpr countries if you use implied consent.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

Empower - September 26-27 2018 In New York

**Comment by damianvimn** [comment]
But on android when I enable implied consent, there is no "Decline All" button. Only "Accept All" and "Manage Preferences".

**Comment by jwheeler66** [comment]
That’s by design as well

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

Empower - September 26-27 2018 In New York

**Comment by damianvimn** [comment]
Ok. Thank you for clarifications. I'm closing the issue as I don't have more questions and initial problem seems not to be a bug :)
