### ISSUE TITLE
Text value overlaps checkbox in 'Privacy Preferences'

### ISSUE THREAD

**Issue by michalvimn** [Crownpeak/AppNotice_Triangle_android_aar#28]
As stated above 
<img width="507" alt="screen shot 2018-09-24 at 16 59 20" src="https://user-images.githubusercontent.com/43540134/45960077-ac2bc600-c01b-11e8-9202-e9ae7d341549.png">

**Comment by vinaychencharam** [comment]
Check out this new verion 2.2.2.5. Hopefully this works. Lmk if you have any issues. 
Thanks
