### ISSUE TITLE
Unable to quit application or close dialog when pressing back button

### ISSUE THREAD

**Issue by damianvimn** [Crownpeak/AppNotice_Triangle_android_aar#29]
Hello. When dialog with consents is presented (phone has UK language) pressing back button shows Activity with title "Your Consent is Required". Is there any possibility to change this behaviour? For example to quit app?

**Comment by vinaychencharam** [comment]
Hi @damianvimn, resolved this issue. Check out this new verion 2.2.3.
Thanks
