### ISSUE TITLE
showManagePreferences crash when support lib v. 28.0.0 is used

### ISSUE THREAD

**Issue by mariuszvimn** [Crownpeak/AppNotice_Triangle_android_aar#31]
Steps to reproduce:
- App uses AppNotice v.2.2.2.4
- App uses android support library v.28.0.0
- App crashes when showing "Manage preferences" screen

This is a critical issue for our app. Can we ask you to provide a new version with the fix?

**Comment by vinaychencharam** [comment]
Hi @mariuszvimn 
This issue has been resolved in the latest versions. Checkout version 2.2.6(latest) which has CompileSDK version targeted to 28 and uses support library v.28.0.0

**Comment by mariuszvimn** [comment]
We cannot download this version. Can you make sure that it is properly published?
